# Generated by Django 5.1.6 on 2025-09-11 15:47

from django.db import migrations


DEFAULT_CATEGORIES = [
    "Electronics",
    "Fashion",
    "Home & Garden",
    "Toys & Games",
    "Sports & Outdoors",
]


def create_default_categories(apps, schema_editor):
    Category = apps.get_model('auctions', 'Category')
    for name in DEFAULT_CATEGORIES:
        Category.objects.get_or_create(name=name)


def remove_default_categories(apps, schema_editor):
    Category = apps.get_model('auctions', 'Category')
    Category.objects.filter(name__in=DEFAULT_CATEGORIES).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_categories, remove_default_categories),
    ]
